# Generated by Django 5.2.7 on 2025-10-21 13:33

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('species', models.CharField(choices=[('chien', 'Chien'), ('chat', 'Chat'), ('lapin', 'Lapin'), ('cheval', 'Cheval'), ('vache', 'Vache'), ('cochon', 'Cochon'), ('chevre', 'Chèvre'), ('mouton', 'Mouton'), ('poule', 'Poule'), ('lion', 'Lion'), ('tigre', 'Tigre'), ('elephant', 'Éléphant'), ('girafe', 'Girafe'), ('zebre', 'Zèbre'), ('gorille', 'Gorille'), ('chimpanze', 'Chimpanzé'), ('panda', 'Panda'), ('ours_polaire', 'Ours polaire'), ('leopard', 'Léopard'), ('rhinoceros', 'Rhinocéros'), ('hippopotame', 'Hippopotame'), ('crocodile', 'Crocodile'), ('lama', 'Lama'), ('autruche', 'Autruche'), ('pelican', 'Pélican'), ('flamant_rose', 'Flamant rose'), ('serpent', 'Serpent'), ('tortue_geante', 'Tortue géante'), ('kangourou', 'Kangourou')], max_length=255)),
                ('enclosure', models.CharField(max_length=255)),
                ('caretaker', models.CharField(choices=[('jean_kabasela', 'Jean Kabasela'), ('marie_lumbala', 'Marie Lumbala'), ('paul_mbayo', 'Paul Mbayo'), ('sophie_nkosi', 'Sophie Nkosi')], max_length=255)),
                ('health_status', models.CharField(choices=[('bon', 'Bon'), ('moyen', 'Moyen'), ('critique', 'Critique'), ('en_traitement', 'En traitement'), ('modéré', 'Modéré')], max_length=255)),
                ('is_being_treated', models.BooleanField(default=False)),
                ('last_control', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ZooParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('currency', models.CharField(choices=[('USD', 'usd'), ('CDF', 'cdf')], max_length=12)),
                ('address', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('Français', 'fr'), ('Anglais', 'en'), ('Espagnol', 'es'), ('Portugais', 'pt'), ('Allemand', 'de'), ('Italien', 'it'), ('Chinois', 'zh'), ('Japonais', 'ja'), ('Coréen', 'ko'), ('Arabe', 'ar'), ('Russe', 'ru'), ('Swahili', 'sw'), ('Lingala', 'ln'), ('Kikongo', 'kg'), ('Haoussa', 'ha')], max_length=255)),
                ('format_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('role', models.CharField(choices=[('Visiteur', 'Visiteur'), ('Personel', 'personel')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'draft')], max_length=10)),
                ('messages', models.CharField(choices=[('Important', 'Important'), ('Pertinant', 'Pertinant'), ('Urgent', 'Urgent')], max_length=255)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('day', models.CharField(choices=[('monday', 'Lundi'), ('tuesday', 'Mardi'), ('wednesday', 'Mercredi'), ('thursday', 'Jeudi'), ('friday', 'Vendredi'), ('saturday', 'Samedi'), ('sunday', 'Dimanche')], max_length=10)),
                ('description', models.TextField()),
                ('Event_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('participants', models.ManyToManyField(related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('veterinaire', 'Vétérinaire'), ('responsable_soigneurs', 'Responsable soigneurs'), ('soigneur', 'Soigneur'), ('responsable_accueil', 'Responsable accueil'), ('guide_touristique', 'Guide touristique'), ('technicien_maintenance', 'Technicien maintenance')], max_length=50)),
                ('department', models.CharField(choices=[('soins_animaux', 'Soins animaux'), ('veterinaire', 'Vétérinaire'), ('visites', 'Visites guidées'), ('maintenance', 'Maintenance'), ('administration', 'Administration'), ('securite', 'Sécurité'), ('accueil', 'Accueil'), ('finances', 'Finances'), ('communication', 'Communication'), ('recherche', 'Recherche'), ('restauration', 'Restauration'), ('nettoyage', 'Nettoyage'), ('informatique', 'Informatique'), ('logistique', 'Logistique'), ('gestion_animaux', 'Gestion des animaux')], max_length=50)),
                ('hire_date', models.DateField()),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('primary_currency', models.CharField(choices=[('USD', 'usd'), ('CDF', 'cdf')], max_length=10)),
                ('date', models.DateField()),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('type_ticket', models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP'), ('etudiant', 'Étudiant'), ('famille', 'Famille'), ('groupe', 'Groupe')], max_length=10)),
                ('category', models.CharField(choices=[('national', 'National'), ('expatrie', 'Expatrié'), ('diplomatique', 'Diplomatique')], max_length=15)),
                ('visit_date', models.CharField(choices=[('monday', 'Lundi'), ('tuesday', 'Mardi'), ('wednesday', 'Mercredi'), ('thursday', 'Jeudi'), ('friday', 'Vendredi'), ('saturday', 'Samedi'), ('sunday', 'Dimanche')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('valide', 'Valide'), ('annule', 'Annulé'), ('en_attente', 'En attente')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_reservation', models.CharField(choices=[('adulte', 'Adulte'), ('enfant', 'Enfant'), ('groupe', 'Groupe'), ('vip', 'VIP'), ('etudiant', 'Étudiant')], max_length=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arrival_time', models.TimeField()),
                ('has_booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='zooApi.event')),
                ('visitors', models.ManyToManyField(related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('tickets', models.ManyToManyField(related_name='reservations', to='zooApi.ticket')),
            ],
        ),
    ]
