# Generated by Django 5.2.7 on 2025-10-18 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooApi', '0002_event_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ticket', models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP'), ('etudiant', 'Étudiant'), ('famille', 'Famille'), ('groupe', 'Groupe')], max_length=10)),
                ('visit_date', models.CharField(choices=[('monday', 'Lundi'), ('tuesday', 'Mardi'), ('wednesday', 'Mercredi'), ('thursday', 'Jeudi'), ('friday', 'Vendredi'), ('saturday', 'Samedi'), ('sunday', 'Dimanche')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_reservation', models.CharField(choices=[('adulte', 'Adulte'), ('enfant', 'Enfant'), ('groupe', 'Groupe'), ('vip', 'VIP'), ('etudiant', 'Étudiant')], max_length=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arrival_time', models.TimeField()),
                ('has_booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='zooApi.event')),
                ('visitors', models.ManyToManyField(related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('tickets', models.ManyToManyField(related_name='reservations', to='zooApi.ticket')),
            ],
        ),
    ]
